services: 

  db:
    image: postgres:16.1

    ports: 
      - "5432:5432"

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: finance_db
    restart: always
    volumes: 
      #- pgdata:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d:ro

# volumes:
#   pgdata: